### ISSUE TITLE
运行报错了

### ISSUE THREAD

**Issue by yzh52521** [webman-tech/laravel-console#2]
PHP Fatal error:  Uncaught Error: Call to undefined method Illuminate\Container\Container::runningUnitTests() in /vendor/illuminate/console/Concerns/ConfiguresPrompts.php:27

**Comment by krissss** [comment]
提供一下最简复现步骤

**Comment by yzh52521** [comment]
illuminate/console 10

**Comment by yzh52521** [comment]
> 提供一下最简复现步骤

illuminate/console 9 正常

**Comment by krissss** [comment]
具体执行的啥命令啊，list 能正常显示吗，https://github.com/webman-tech/laravel-console/actions/runs/5031024186/job/13626655770  10.x 的版本在测试下是ok的

**Comment by yzh52521** [comment]
> 具体执行的啥命令啊，list 能正常显示吗，https://github.com/webman-tech/laravel-console/actions/runs/5031024186/job/13626655770 10.x 的版本在测试下是ok的

list 可以 
自定义的都不可以

**Comment by yzh52521** [comment]
app\command 下的都运行都报错

**Comment by krissss** [comment]
应该是 10.17 版本改动引起的，晚点看下如何修复

**Comment by krissss** [comment]
https://github.com/laravel/framework/pull/47992

**Comment by krissss** [comment]
更新到 1.0.3 可以了
