### ISSUE TITLE
示例运行报错了

### ISSUE THREAD

**Issue by Mr-ShiHuaYu** [webman-tech/laravel-console#4]
D:\4.PHP\Code\webman-zbcms>php artisan mail:send 1
PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(D:\4.PHP\Code\webman-zbcms/plugin/admin/D:\4.PHP\Code\webman-zbcms/plugin/admin/command): 文件名、目录名或卷标语法不正确� (code: 123) in D:\4.PHP\Code\webman-zbcms\vendor\webman-tech\laravel-consphp:171
Stack trace:
#0 D:\4.PHP\Code\webman-zbcms\vendor\webman-tech\laravel-console\src\Kernel.php(171): RecursiveDirectoryIterator->__construct('D:\\4.PHP\\Code\\w...')
#1 D:\4.PHP\Code\webman-zbcms\vendor\webman-tech\laravel-console\src\Kernel.php(144): WebmanTech\LaravelConsole\Kernel->installCommands('D:\\4.PHP\\Code\\w...', 'plugin\\admin\\D:...')
#2 D:\4.PHP\Code\webman-zbcms\vendor\webman-tech\laravel-console\src\Kernel.php(108): WebmanTech\LaravelConsole\Kernel->loadCommands()
#3 D:\4.PHP\Code\webman-zbcms\vendor\webman-tech\laravel-console\src\Kernel.php(51): WebmanTech\LaravelConsole\Kernel->bootstrap()
#4 D:\4.PHP\Code\webman-zbcms\artisan(24): WebmanTech\LaravelConsole\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}
  thrown in D:\4.PHP\Code\webman-zbcms\vendor\webman-tech\laravel-console\src\Kernel.php on line 171

Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(D:\4.PHP\Code\webman-zbcms/plugin/admin/D:\4.PHP\Code\we
bman-zbcms/plugin/admin/command): 文件名、目录名或卷标语法不正确� (code: 123) in D:\4.PHP\Code\webman-zbcms\vendor\webman-tech\laravel-console\src\Kernel.php:171
Stack trace:
#0 D:\4.PHP\Code\webman-zbcms\vendor\webman-tech\laravel-console\src\Kernel.php(171): RecursiveDirectoryIterator->__construct('D:\\4.PHP\\Code\\w...')
#1 D:\4.PHP\Code\webman-zbcms\vendor\webman-tech\laravel-console\src\Kernel.php(144): WebmanTech\LaravelConsole\Kernel->installCommands('D:\\4.PHP\\Code\\w...', 'plugin\\admin\\D:...')
#2 D:\4.PHP\Code\webman-zbcms\vendor\webman-tech\laravel-console\src\Kernel.php(108): WebmanTech\LaravelConsole\Kernel->loadCommands()
#3 D:\4.PHP\Code\webman-zbcms\vendor\webman-tech\laravel-console\src\Kernel.php(51): WebmanTech\LaravelConsole\Kernel->bootstrap()
#4 D:\4.PHP\Code\webman-zbcms\artisan(24): WebmanTech\LaravelConsole\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}
  thrown in D:\4.PHP\Code\webman-zbcms\vendor\webman-tech\laravel-console\src\Kernel.php on line 171

**Comment by krissss** [comment]
升级到 1.0.4
